---
# File:    roles/supervisor/tasks/SupervisorStartup.yml
# Purpose: re-useable task to startup a Supervisord instance - task can be included in task files for other roles

# parameterised task which can be used to startup the Supervisor application
- name: startup Supervisor
  service: name=supervisord state=started enabled=yes pattern=supervisord
  sudo: yes
  
# wait for  the supervisord pid file to be present to confirm Supervisor has successfully started, task will fail after 60 seconds if the pid file is not present
- name: wait for Supervisor to startup
  wait_for: path={{ supervisor_pid_path }} state=present delay=10 timeout=60
  register: supervisor_status
    
