---
# File:    roles/supervisor/tasks/SupervisorStartService.yml
# Purpose: re-useable task which can be included in task files for other roles

# parameterised task which can be used to start a registered Supervisor process
- name: start a Supervisor process < {{ supervisor_process_desc }} > 
  supervisorctl: name={{ supervisor_process_name }} state=started config={{ supervisor_config_dir }}/supervisord.conf supervisorctl_path={{ supervisorctl_bin }}
    