#!/bin/bash
# Easy to run build a Dockerfile to gen a docker image
# Author by Will

# docker build option
# --no-cache=false Do not use cache when building the image  
# -q, --quiet=false Suppress the verbose output generated by the containers  
# --rm=true Remove intermediate containers after a successful build  
# -t, --tag="" Repository name (and optionally a tag) to be applied to the resulting image in case of success
docker build --no-cache=false -t centos_tianxun_dr_jekyll_base:dev .
